services:
  db-dev:
    container_name: db-dev-container
    image: mysql:8.0
    volumes:  
      - db-volume:/var/lib/mysql
    ports:
      - "3310:3306"
    env_file:
      - .env

volumes:
  db-volume: