spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: api
  web:
    resources:
      add-mappings: 'false'
  datasource:
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

  security:
    oauth2:
      client:
        registration:
          google:
            # 발급 받은 Client ID
            client-id: ${google-client-id}
            # 발급 받은 Client Secret
            client-secret: ${google-client-secret}
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
  #
  #          naver:
  #            client-id: # 발급 받은 Client ID
  #            client-secret: # 발급 받은 Client Secret
  #            client-authentication-method: client_secret_post
  #            authorization-grant-type: authorization_code
  #            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
  #            #            scope:
  #            #              - name
  #            #              - email
  #            #              - profile_image
  #            client-name: Naver
  #
  #          kakao:
  #            client-id: # 발급 받은 Client ID
  #            client-secret: # 발급 받은 Client Secret
  #            client-authentication-method: client_secret_post
  #            authorization-grant-type: authorization_code
  #            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
  #              - profile_nickname
  #              - profile_image
  #              - account_email
  #            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
  #            client-name: Kakao
  #
  #        provider:
  #          naver:
  #            authorization-uri: https://nid.naver.com/oauth2.0/authorize
  #            token-uri: https://nid.naver.com/oauth2.0/token
  #            user-info-uri: https://openapi.naver.com/v1/nid/me
  #            user-info-authentication-method: header
  #            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
  #          kakao:
  #            authorization-uri: https://kauth.kakao.com/oauth/authorize
  #            token-uri: https://kauth.kakao.com/oauth/token
  #            user-info-uri: https://kapi.kakao.com/v2/user/me
  #            user-info-authentication-method: header
  #            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

logging:
  level:
    org:
      springframework:
        web:
          nodeValue: DEBUG
          filter:
            CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: ${jwt_secret}
domain: ${DOMAIN}
server:
  port: '8080'
