spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: api
  web:
    resources:
      add-mappings: false
  datasource:
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            # 발급 받은 Client ID
            client-id: ${google-client-id}
            # 발급 받은 Client Secret
            client-secret: ${google-client-secret}
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
logging:
  level:
    org:
      springframework:
        web:
          nodeValue: DEBUG
          filter:
            CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: ${JWT_SECRET}

domain: ${DOMAIN}
server:
  port: 8080
